export const DEFAULT_PROFILE_IMAGE = "/assets/images/profile-img.jpg";

export const allClasses = [
  {
    value: "JSS1",
    label: "Junior Secondary School 1",
  },
  {
    value: "JSS2",
    label: "Junior Secondary School 2",
  },
  {
    value: "JSS3",
    label: "Junior Secondary School 3",
  },
  {
    value: "SSS1",
    label: "Senior Secondary School 1",
  },
  {
    value: "SSS2",
    label: "Senior Secondary School 2",
  },
  {
    value: "SSS3",
    label: "Senior Secondary School 3",
  },
];

export const sections = ["A", "B", "C", "D"];
export const relationships = ["Father", "Mother", "Guardian", "Others"];

export const studentStatuses = ["PENDING", "APPROVED", "REJECTED"];

export const subjectStatuses = ["ACTIVE", "INACTIVE", "DRAFT"];
export const staffStatuses = ["ACTIVE", "INACTIVE", "ON LEAVE"];
export const subjectTypes = ["CORE", "ELECTIVE", "VOCATIONAL"];
export const departments = [
  "ADMINISTRATION",
  "MATHEMATICS",
  "SCIENCE",
  "ENGLISH",
  "LIBRARY SERVICE",
];
export const allRoles = [
  "TEACHER",
  "PRINCIPAL",
  "ADMIN",
  "COUNSELOR",
  "LIBRARIAN",
];
export const feesStatus = ["PAID", "PENDING", "OVERDUE", "PARTIAL"];

export const schoolTypes = [
  "Primary School",
  "Secondary School",
  "Combined School (Primary & Secondary)",
  "Tertiary Institution",
];

export const ownershipTypes = ["Government", "Private", "Mission", "Community"];
export const academicTerms = ["First Term", "Second Term", "Third Term"];
export const termsPerSession = ["2 Terms", "3 Terms", "4 Terms (Quarters)"];
export const gradingSystems = [
  "Percentage (0-100)",
  "Letter Grade (A-F)",
  "GPA (0.0-4-0)",
  "Points (1-10)",
];

export const years = Array.from(
  { length: new Date().getFullYear() - 1960 + 1 },
  (_, i) => (1960 + i).toString()
);

export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
  "FCT (Abuja)",
] as const;

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const timezones = [
  {
    label: "Africa/Lagos (WAT)",
    value: "WAT",
  },
  {
    label: "UTC",
    value: "UTC",
  },
];

export const genders = ["Male", "Female"];
export const titles = ["Mr.", "Mrs.", "Miss", "Master"];
